### ISSUE TITLE
faulty link?

### ISSUE THREAD

**Issue by BernhardEllmann** [LibreSolar/mppt-2420-rc#2]
right-click on 
mppt-2420-rc_bom_v0.1.1.csv
at 
https://github.com/LibreSolar/mppt-2420-rc/tree/master/bom

and click on 
"Ziel speichern unter .. " 
yields some wrong file,

whereas using "clone or Download" / "download ZIP" works well.

**Comment by martinjaeger** [comment]
You should left-click on the link and then download the raw file. That's the way how github displays content of text files.
