### ISSUE TITLE
Schottky Diode SS14FL discontinued

### ISSUE THREAD

**Issue by BernhardEllmann** [LibreSolar/mppt-2420-rc#4]
Schottky Diode SS14FL dircontinued acc. to Mouser homepage (2020-06-13)

--> what should be used as a replacement?

**Comment by martinjaeger** [comment]
An Alternative is already mentioned in the "Alternative" column of the BOM: Nexperia PMEG4010EGWX

Or you use the same 60V / 2A variant as suggested for the CAN bus port (see other issue).

**Comment by BernhardEllmann** [comment]
oh, yes, sorry. 
I had to modify my excel for several reasons, and I happened to delete this information
