### ISSUE TITLE
J5 external temperature sensor

### ISSUE THREAD

**Issue by BernhardEllmann** [LibreSolar/mppt-2420-rc#9]
what happens if J5 remains open?

If I want to use J5: 
- what sensor do i need to use?
- what connector matches with J5?
Please specify

**Comment by martinjaeger** [comment]
The firmware assumes 25°C if no external sensor is connected. And as Li-Ion charging voltages are not temperature-dependent, it's only relevant for lead-acid batteries.

You can use any wired 10k NTC with a connector from Phoenix Contact FMC 1,5 3,81 series (or similar one from other brands). A suitable Phoenix Contact part number is 1745894.

Thanks for the remark, I will add this to the schematic.

**Comment by BernhardEllmann** [comment]
ok, fine, thanks a lot!
